name: Labeling new issue
on:
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"
  issues:
    types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-not-allowed: '["Stale","Pendente de informações","Falta de informações"]'
